# Agenda
* Numpy
* Pandas
* Lab


# Introduction


## Create a new notebook for your code-along:

From our submission directory, type:
    
    jupyter notebook

From the IPython Dashboard, open a new notebook.
Change the title to: "Numpy and Pandas"

# Introduction to Numpy

* Overview
* ndarray
* Indexing and Slicing

More info: [http://wiki.scipy.org/Tentative_NumPy_Tutorial](http://wiki.scipy.org/Tentative_NumPy_Tutorial)


## Numpy Overview

* Why Python for Data? Numpy brings *decades* of C math into Python!
* Numpy provides a wrapper for extensive C/C++/Fortran codebases, used for data analysis functionality
* NDAarray allows easy vectorized math and broadcasting (i.e. functions for vector elements of different shapes)

In [2]:
import numpy as np

### Creating ndarrays

An array object represents a multidimensional, homogeneous array of fixed-size items. 

In [14]:
# Creating arrays
a = np.zeros((3))
b = np.ones((2,3))
c = np.random.randint(1,10,(2,3,4))
d = np.arange(0,11,1)
print c


[[[9 8 6 7]
  [7 7 9 6]
  [4 7 9 4]]

 [[6 6 5 2]
  [3 9 7 1]
  [9 8 2 1]]]


What are these functions?

    arange?

In [15]:
c = np.random.randint(5)
print c 

3


In [ ]:
# Note the way each array is printed:
a,b,c,d

In [ ]:
## Arithmetic in arrays is element wise

In [ ]:
a = np.array( [20,30,40,50] )
b = np.arange( 4 )
b

In [ ]:
c = a-b
c

In [5]:
b**2

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [7]:
np.array( [ [1, 1, 2] [1,2,3] ] )

TypeError: list indices must be integers, not tuple

## Indexing, Slicing and Iterating

In [8]:
# one-dimensional arrays work like lists:
a = np.arange(10)**2
print a

map( lambda x: x**2, range(10))

[ 0  1  4  9 16 25 36 49 64 81]


[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [10]:
someList = [1,2,3]

In [ ]:
a

In [ ]:
a[2:5]

In [ ]:
# Multidimensional arrays use tuples with commas for indexing
# with (row,column) conventions beginning, as always in Python, from 0

In [11]:
b = np.random.randint(1,100,(4,4))

In [12]:
b

array([[83,  3,  3, 43],
       [56, 53, 39, 17],
       [36, 15, 34, 92],
       [89,  9, 59, 31]])

In [13]:
# Guess the output
print(b[2,3])
print(b[0,0])


92
83


In [ ]:
b[0:3,1],b[:,1]

In [ ]:
b[1:3,:]

# Introduction to Pandas

* Object Creation
* Viewing data
* Selection
* Missing data
* Grouping
* Reshaping
* Time series
* Plotting
* i/o
 

_pandas.pydata.org_

## Pandas Overview

_Source: [pandas.pydata.org](http://pandas.pydata.org/pandas-docs/stable/10min.html)_

In [17]:


import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [18]:
dates = pd.date_range('20140101',periods=6)
dates

DatetimeIndex(['2014-01-01', '2014-01-02', '2014-01-03', '2014-01-04',
               '2014-01-05', '2014-01-06'],
              dtype='datetime64[ns]', freq='D')

In [19]:
df = pd.DataFrame(np.random.randn(6,4),index=dates,columns=list('ABCD'))
z = pd.DataFrame(index = df.index, columns = df.columns)
df.columns

Index([u'A', u'B', u'C', u'D'], dtype='object')

In [ ]:
# Index, columns, underlying numpy data
df.T
df

In [21]:
date1 = dates[0]

In [22]:
print date1.day
print date1.month
print date1.year 

1
1
2014


In [25]:
np.random.randn(6,4)

array([[-1.44109353, -0.24582897,  0.32564777, -0.82266899],
       [ 1.98496562, -1.51997571, -0.97941756,  1.38747009],
       [-0.10660329, -1.08110263, -0.94562164,  0.23475397],
       [-0.22771312, -1.86786083,  0.09279221,  0.49078305],
       [ 0.46861675, -0.85260242, -1.21174669, -0.52023491],
       [-0.12122863,  0.31493727,  1.41833511, -2.04031152]])

In [ ]:
df2 = pd.DataFrame({ 'A' : 1.,
                         'B' : pd.Timestamp('20130102'),
                         'C' : pd.Series(1,index=list(range(4)),dtype='float32'),
                         'D' : np.array([3] * 4,dtype='int32'),
                         'E' : 'foo' })
    

df2

In [24]:
# With specific dtypes
df2.dtypes 

NameError: name 'df2' is not defined

#### Viewing Data

In [28]:
df.sort_values(by='B', inplace =True)

In [29]:
df.head()

A         B         C         D
2014-01-06 -1.136103 -1.337272  1.343567  0.525719
2014-01-04  0.046698 -0.751599 -0.090494  2.063402
2014-01-05  0.428480  0.339783 -0.168571 -0.133268
2014-01-02  0.520191  0.927938  0.158697  0.734208
2014-01-03 -1.371540  1.221441  0.392139  0.728849

In [26]:
df.T

2014-01-01  2014-01-02  2014-01-03  2014-01-04  2014-01-05  2014-01-06
A    1.301956    0.520191   -1.371540    0.046698    0.428480   -1.136103
B    2.456435    0.927938    1.221441   -0.751599    0.339783   -1.337272
C    0.227917    0.158697    0.392139   -0.090494   -0.168571    1.343567
D   -0.874129    0.734208    0.728849    2.063402   -0.133268    0.525719

In [ ]:
df.tail()

In [ ]:
df.index

In [ ]:
df.describe()

In [ ]:
df.sort_values(by='B')
df

### Selection

In [30]:
df[['A','B']]

A         B
2014-01-06 -1.136103 -1.337272
2014-01-04  0.046698 -0.751599
2014-01-05  0.428480  0.339783
2014-01-02  0.520191  0.927938
2014-01-03 -1.371540  1.221441
2014-01-01  1.301956  2.456435

In [31]:
df[0:3] 

A         B         C         D
2014-01-06 -1.136103 -1.337272  1.343567  0.525719
2014-01-04  0.046698 -0.751599 -0.090494  2.063402
2014-01-05  0.428480  0.339783 -0.168571 -0.133268

In [32]:
# By label
print dates 

df.loc[dates[0]]

DatetimeIndex(['2014-01-01', '2014-01-02', '2014-01-03', '2014-01-04',
               '2014-01-05', '2014-01-06'],
              dtype='datetime64[ns]', freq='D')


A    1.301956
B    2.456435
C    0.227917
D   -0.874129
Name: 2014-01-01 00:00:00, dtype: float64

In [33]:
# multi-axis by label
df.loc[:,['A','B']]

df.loc ['2014-01-01': '2014-01-03', ['A', 'B']]

A         B
2014-01-02  0.520191  0.927938
2014-01-03 -1.371540  1.221441
2014-01-01  1.301956  2.456435

In [ ]:
# Date Range
df.loc['20140102':'20140104',['B']]

In [34]:
# Fast access to scalar
df.at[dates[1],'B']

0.92793774124581307

In [ ]:
# iloc provides integer locations similar to np style
df.iloc[3:]

### Boolean Indexing

In [ ]:
df[df.A < 0] # Basically a 'where' operation

### Setting

In [ ]:
df_posA = df.copy() # Without "copy" it would act on the dataset

df_posA[df_posA.A < 0] = -1*df_posA

In [ ]:
df_posA

In [ ]:
#Setting new column aligns data by index
s1 = pd.Series([1,2,3,4,5,6],index=pd.date_range('20140102',periods=6))

In [ ]:
s1

In [ ]:
df['F'] = s1

In [ ]:
df

### Missing Data

In [ ]:
# Add a column with missing data
df1 = df.reindex(index=dates[0:4],columns=list(df.columns) + ['E'])

In [ ]:
df1.loc[dates[0]:dates[1],'E'] = 1

In [ ]:
df1

In [ ]:
# find where values are null
pd.isnull(df1)

### Operations

In [ ]:
df.describe()

In [ ]:
df.mean(),df.mean(1) # Operation on two different axes

### Applying functions

In [ ]:
df

In [1]:
import pandas as pd
df = pd.DataFrame ({ "A" : range(5), "B" : range(5) })
df.head()

A  B
0  0  0
1  1  1
2  2  2
3  3  3
4  4  4

In [3]:
df.drop("C", axis = 0, inplace = True)

ValueError: labels ['C'] not contained in axis

In [5]:
df2 = pd.DataFrame(
    {"firstName" : ["Alex", "Tom"], "lastName" : ["Henry", "Smith"] } )
df2.head()

firstName lastName
0      Alex    Henry
1       Tom    Smith

In [11]:
df2["fullName"] = df2.firstName + " " + df2.lastName

In [35]:
df.head()

A         B         C         D
2014-01-06 -1.136103 -1.337272  1.343567  0.525719
2014-01-04  0.046698 -0.751599 -0.090494  2.063402
2014-01-05  0.428480  0.339783 -0.168571 -0.133268
2014-01-02  0.520191  0.927938  0.158697  0.734208
2014-01-03 -1.371540  1.221441  0.392139  0.728849

In [9]:
def makeFullName(obj):
    #obj returns a list 
    firstName = obj[0]
    lastName = obj[1]
    return firstName + " " + lastName
    
    df2["fullName"] = df2.apply(makeFullName, axis = 1)

In [37]:


df['E'] = df.D.apply(lambda x: x*2) 
df ['F'] = df.D.apply (multiplyBy2)

NameError: name 'multiplyBy2' is not defined

In [36]:
df.head()

A         B         C         D
2014-01-06 -1.136103 -1.337272  1.343567  0.525719
2014-01-04  0.046698 -0.751599 -0.090494  2.063402
2014-01-05  0.428480  0.339783 -0.168571 -0.133268
2014-01-02  0.520191  0.927938  0.158697  0.734208
2014-01-03 -1.371540  1.221441  0.392139  0.728849

In [38]:
df.apply(np.cumsum)

A         B         C         D         E
2014-01-06 -1.136103 -1.337272  1.343567  0.525719  1.051437
2014-01-04 -1.089405 -2.088872  1.253073  2.589121  5.178241
2014-01-05 -0.660925 -1.749089  1.084501  2.455853  4.911705
2014-01-02 -0.140734 -0.821151  1.243199  3.190061  6.380121
2014-01-03 -1.512274  0.400290  1.635338  3.918909  7.837819
2014-01-01 -0.210318  2.856725  1.863254  3.044780  6.089560

In [39]:
df.apply(lambda x: x.max() - x.min())

A    2.673496
B    3.793707
C    1.512138
D    2.937531
E    5.875063
dtype: float64

In [ ]:
# Built in string methods
s = pd.Series(['A', 'B', 'C', 'Aaba', 'Baca', np.nan, 'CABA', 'dog', 'cat'])
s.str.lower()

### Merge

In [16]:
import pandas as np
np.random.randn(10,4)

AttributeError: 'module' object has no attribute 'random'

In [15]:
#Concatenating pandas objects together
df = pd.DataFrame(np.random.randn(10,4))
df

AttributeError: 'module' object has no attribute 'random'

In [ ]:
# Break it into pieces
pieces = [df[:3], df[3:7],df[7:]]
pieces

In [ ]:
pd.concat(pieces)

In [ ]:
# Also can "Join" and "Append"
df

### Grouping


In [ ]:
df = pd.DataFrame({'A' : ['foo', 'bar', 'foo', 'bar',
                       'foo', 'bar', 'foo', 'foo'],
                       'B' : ['one', 'one', 'two', 'three',
                             'two', 'two', 'one', 'three'],
                       'C' : np.random.randn(8),
                       'D' : np.random.randn(8)})

In [ ]:
df

In [ ]:
df.groupby(['A','B']).sum()

### Reshaping

In [ ]:
# You can also stack or unstack levels

In [ ]:
a = df.groupby(['A','B']).sum()

In [ ]:
# Pivot Tables
pd.pivot_table(df,values=['C','D'],index=['A'],columns=['B'])

### Time Series


In [ ]:
import pandas as pd
import numpy as np

In [ ]:
# 100 Seconds starting on January 1st
rng = pd.date_range('1/1/2014', periods=100, freq='S')

In [ ]:
# Give each second a random value
ts = pd.Series(np.random.randint(0, 500, len(rng)), index=rng)

In [ ]:
ts

In [ ]:
# Built in resampling
ts.resample('1Min').mean() # Resample secondly to 1Minutely

In [ ]:
# Many additional time series features
ts. #use tab

### Plotting


In [ ]:
ts.plot()

In [ ]:
def randwalk(startdate,points):
    ts = pd.Series(np.random.randn(points), index=pd.date_range(startdate, periods=points))
    ts=ts.cumsum()
    ts.plot()
    return(ts)

In [ ]:
# Using pandas to make a simple random walker by repeatedly running:
a=randwalk('1/1/2012',1000)

In [ ]:
# Pandas plot function will print with labels as default

In [ ]:
df = pd.DataFrame(np.random.randn(100, 4), index=ts.index,columns=['A', 'B', 'C', 'D'])
df = df.cumsum()
plt.figure();df.plot();plt.legend(loc='best') #

### I/O
I/O is straightforward with, for example, pd.read_csv or df.to_csv

#### The benefits of open source:

Let's look under x's in plt modules

# Next Steps

**Recommended Resources**

Name | Description
--- | ---
[Official Pandas Tutorials](http://pandas.pydata.org/pandas-docs/stable/10min.html) | Wes & Company's selection of tutorials and lectures
[Julia Evans Pandas Cookbook](https://github.com/jvns/pandas-cookbook) | Great resource with examples from weather, bikes and 311 calls
[Learn Pandas Tutorials](https://bitbucket.org/hrojas/learn-pandas) | A great series of Pandas tutorials from Dave Rojas
[Research Computing Python Data PYNBs](https://github.com/ResearchComputing/Meetup-Fall-2013/tree/master/python) | A super awesome set of python notebooks from a meetup-based course exclusively devoted to pandas